# Secrets https://esphome.io/guides/faq.html?highlight=secrets
substitutions:
  device_name: name

esphome:
  name: ${device_name}
  platform: ESP8266
  board: nodemcuv2
  includes:
    - VL53L1X_people_counter.h
# put SparkFun VL53L1X Arduino Library in your global libraries:
# https://github.com/sparkfun/SparkFun_VL53L1X_Arduino_Library
  libraries:
    - "SparkFun VL53L1X Arduino Library"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG
  esp8266_store_log_strings_in_flash: False

api:

ota:

# mqtt:
#   broker: !secret mqtt_ip_adress
#   port: 1883
#   username: !secret mqtt_user
#   password: !secret mqtt_password

#   - platform: status
#     name: "${device_name} Status"


sensor: 
  - platform: wifi_signal
    name: "${device_name} WiFi Signal"

  - platform: custom
    lambda: |-
      auto my_sensor = new VL53L1X_people_counter();
      App.register_component(my_sensor);
      return {my_sensor->people_counter};
    sensors:
    - name: "My Custom People Counter Sensor"

  # Esphome custom compenent example
  # - platform: custom
  #   lambda: |-
  #     auto my_sensor = new MyCustomSensor();
  #     App.register_component(my_sensor);
  #     return {my_sensor->temperature_sensor, my_sensor->pressure_sensor};
  
  #   sensors:
  #   - name: "My Custom Temperature Sensor"
  #     unit_of_measurement: °C
  #     accuracy_decimals: 1
  #   - name: "My Custom Pressure Sensor"
  #     unit_of_measurement: hPa
  #     accuracy_decimals: 2

switch:
  - platform: restart
    id: reboot
    name: "Restart ${device_name}"

status_led:
  pin:
    number: GPIO13
    inverted: yes